"""init tables

Revision ID: 312d97ea0ff7
Revises: 
Create Date: 2026-06-29 18:13:46.710171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '312d97ea0ff7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('morning_logs',
    sa.Column('sleep_date', sa.String(), nullable=False),
    sa.Column('raw_sleep', sa.Text(), nullable=True),
    sa.Column('raw_hrv', sa.Text(), nullable=True),
    sa.Column('raw_daily', sa.Text(), nullable=True),
    sa.Column('report', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('sleep_date')
    )
    op.create_table('processed_activities',
    sa.Column('label_id', sa.String(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('label_id')
    )
    op.create_table('risk_logs',
    sa.Column('check_date', sa.String(), nullable=False),
    sa.Column('signals', sa.Text(), nullable=True),
    sa.Column('report', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('check_date')
    )
    op.create_table('run_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('raw_activity', sa.Text(), nullable=True),
    sa.Column('raw_daily', sa.Text(), nullable=True),
    sa.Column('coaching', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weekly_logs',
    sa.Column('week_start', sa.String(), nullable=False),
    sa.Column('raw_daily', sa.Text(), nullable=True),
    sa.Column('raw_sessions', sa.Text(), nullable=True),
    sa.Column('report', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('week_start')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weekly_logs')
    op.drop_table('run_logs')
    op.drop_table('risk_logs')
    op.drop_table('processed_activities')
    op.drop_table('morning_logs')
    # ### end Alembic commands ###
