"""init tables

Revision ID: eabfc91d7ab5
Revises: 
Create Date: 2026-07-08 14:40:42.450193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eabfc91d7ab5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('coros_user_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_coros_user_id'), 'users', ['coros_user_id'], unique=True)
    op.create_table('morning_logs',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sleep_date', sa.String(), nullable=False),
    sa.Column('raw_sleep', sa.Text(), nullable=True),
    sa.Column('raw_hrv', sa.Text(), nullable=True),
    sa.Column('raw_daily', sa.Text(), nullable=True),
    sa.Column('report', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'sleep_date')
    )
    op.create_table('processed_activities',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('label_id', sa.String(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'label_id')
    )
    op.create_table('risk_logs',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('check_date', sa.String(), nullable=False),
    sa.Column('signals', sa.Text(), nullable=True),
    sa.Column('report', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'check_date')
    )
    op.create_table('run_logs',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('raw_activity', sa.Text(), nullable=True),
    sa.Column('raw_daily', sa.Text(), nullable=True),
    sa.Column('coaching', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'id')
    )
    op.create_table('weekly_logs',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.String(), nullable=False),
    sa.Column('raw_daily', sa.Text(), nullable=True),
    sa.Column('raw_sessions', sa.Text(), nullable=True),
    sa.Column('report', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'week_start')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weekly_logs')
    op.drop_table('run_logs')
    op.drop_table('risk_logs')
    op.drop_table('processed_activities')
    op.drop_table('morning_logs')
    op.drop_index(op.f('ix_users_coros_user_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
